dist: bionic
sudo: required
language: c

env:
  global:
  - OPAMYES="true"
  - OPAMJOBS="2"
  matrix:
  - OCAML=4.04.2
  - OCAML=4.05.0
  - OCAML=4.06.0
  - OCAML=4.06.1
  - OCAML=4.07.0
  - OCAML=4.07.1
  - OCAML=4.08.0
  - OCAML=4.08.1
  - OCAML=4.09.0
  - OCAML=4.10.0
# Wait until ocaml-base-compiler.4.09.1 arrives to opam-repository
#  - OCAML=4.09.1

script:
  - sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.6/opam-2.0.6-x86_64-linux -o /usr/bin/opam
  - sudo chmod 755 /usr/bin/opam
  - opam init --disable-sandboxing -c $OCAML
  - opam switch set $OCAML
  - eval $(opam env)
  - opam pin add -n -k path ppx_import .
  - opam install --deps-only -d -t ppx_import
  - opam install -d -t -v ppx_import
